### PR TITLE
Development

### PR DESCRIPTION
**Pull request by arashasadabadi**

### CODE REVIEW

**Comment by jrawbits** [comment]
It looks like the Test1 model is not running - adding the MM Modules leads (weirdly) to an earlier failure:
```
[1] "2020-03-24 17:32:52 -- Starting module 'CalculateVehicleOwnCost' for year '2010'."
Error: Column name `Marea` must not be duplicated.
```
So there may be some problem with the input specification for the MM Module(s)

**Comment by jrawbits** [comment]
This fix works to address the problem I reported with Marea.  Note that running the model yields a series of messages like this:
```
46: unnest() has a new interface. See ?unnest for details.
Try `df %>% unnest(c(id, y))`, with `mutate()` if needed
```
That's a problem with tidyverse version creep... We will need to fix that problem before we can release the MM code.

**Comment by arashasadabadi** [comment]
Hi Jeremy,

The tidyr version was causing the warning problem for nest() function. I fixed that one and now you should have a clean version.

Thanks,
Arash

**Comment by arashasadabadi** [comment]
The tidyr version was causing the warning problem for nest() function. I fixed that one and now you should have a clean version.

**Comment by arashasadabadi** [comment]
added a new pull request to mm_debug branch

**Comment by jrawbits** [comment]
Working version has now been pushed to mm_debug branch in VisionEval-dev (including fixing warnigns from nest function API).

**Pull request closed without merging**
