### PR TITLE
Fix a bug in writeToTableRD to retain dataset attributes when writing to existing dataset in datastore

### PR DESCRIPTION
**Pull request by gregorbj**
This is a bug fix to the writeToTableRD function. Currently when a dataset in the datastore is being overwritten with revised data, many or all of the attributes of the dataset in the datastore will be removed. This happens because the dataset first gets read from the datastore (by the readFromTableRD function) before rewriting and unless the dataset attributes are read as well, they will be overwritten with NA when the dataset is rewritten. The bug fix is to set the ReadAttr argument of the readFromTableRD function equal to TRUE.

### CODE REVIEW

**Comment by dflynn-volpe** [comment]
Hi Brian --

The Travis checks have been changed to be a bit more strict now. Your pull request is one of the first ones under this new testing, and the Travis build stopped due to two warnings. 

After a bit of reading ([here](https://cran.r-project.org/doc/manuals/r-patched/R-exts.html#Package-Dependencies) and [here](https://github.com/r-lib/devtools/issues/1742)), I see that it is in the DESCRIPTION of VESyntheticFirms and VETransportSupplyUse. The recommendation is here:

```
It is inadvisable to use a dependence on R with patchlevel (the third digit) other than zero.
```

Can you change the following: 

https://github.com/gregorbj/VisionEval-Dev/blob/development/sources/modules/VESyntheticFirms/DESCRIPTION#L13 
to `Depend: R (>= 3.3.0)`

And

https://github.com/gregorbj/VisionEval-Dev/blob/development/sources/modules/VETransportSupplyUse/DESCRIPTION#L14

to 'Depends: R (>= 3.4.0)`

?

I also see that [VEReports](https://github.com/gregorbj/VisionEval-Dev/blob/development/sources/modules/VEReports/DESCRIPTION#L14) is going to have the same issue.

The error are here:
```
 
── Checking ──────────────────────────────────────────────── VESyntheticFirms ──
   
   WARNING
   Dependence on R version ‘3.3.2’ not with patchlevel 0

── R CMD check results ─────────────────────────── VETransportSupplyUse 0.1 ────
Duration: 24.8s
❯ checking DESCRIPTION meta-information ... WARNING
  Dependence on R version ‘3.4.2’ not with patchlevel 0
 ```

**Comment by gregorbj** [comment]
Committed changes to DESCRIPTION files for VESyntheticFirms, VETransportSupplyUse, and VEReports of gregorbj fork.

**Comment by jrawbits** [comment]
We also need to make a corresponding change to VEScenario.

**Comment by gregorbj** [comment]
I just committed the change to VEScenario Depends from 3.4 to 3.4.0 in the gregorbj fork.

**Comment by dflynn-volpe** [comment]
Thanks, Brian -- it looks like we need to add a few more documentation tags for data sets, including the default values from DvmtModels_ls, EvModelData_ls, PhevModelData_ls, TripLengthModel_ls, and VehTripModels_ls for VEHouseholdTravel. For example, in [CalculateTravelTemand.R](https://github.com/VisionEval/VisionEval-Dev/blob/development/sources/modules/VEHouseholdTravel/R/CalculateTravelDemand.R#L82).

Also, HhAllocationModelCoeff is showing the same warning in VELandUse, although the identical object HhAllocationModelCoeff_df is documented. In [CalculateBasePlaceTypes.R](https://github.com/VisionEval/VisionEval-Dev/blob/development/sources/modules/VELandUse/R/CalculateBasePlaceTypes.R#L19), is there a reason why HhAllocationModelCoef isn't just stored as HhAllocationModelCoef_df?

This is a lot more work than you bargained for when submitting this bug fix, so we can work of fixing these documentation warnings to get it to pass Travis checks.

**Comment by gregorbj** [comment]
CalculateTravelDemand.R and CalculateBasePlaceTypes.R are scripts used by VE-RPAT, not VE-RSPM or VE-State. Changes to those scripts should be made by someone at RSG.

**Comment by dflynn-volpe** [comment]
@gregorbj, your bug fix to datastore.R has been incorporated via this PR [here](https://github.com/VisionEval/VisionEval-Dev/commit/39c21236c6e72035704062c39e5b07b9bb49bd93#diff-6f8c46c2833ee84b913bc4bd6e86ed80).
We have gone back to a more relaxed testing, so that the build does not stop due to warnings in Travis, see the change [here](https://github.com/VisionEval/VisionEval-Dev/blob/development/.travis.yml#L14).

I'm going to close this PR now, and we can keep in mind the documentation of datasets if we want to go back to the more strict (warnings are errors) testing in Travis.

**Pull request closed without merging**
