### PR TITLE
Resubmit VETravelDemandMM module

### PR DESCRIPTION
**Pull request by lmwang9527**
This is to resubmit the VETravelDemandMM package as a VE module using `git submodule`, so that the git history of the VETravelDemandMM package is preserved at https://github.com/cities-lab/VETravelDemandMM

Travis-CI test status 
  - for the VETravelDemandMM package alone: [Travis-CI Build Status](https://travis-ci.org/cities-lab/VETravelDemandMM)
  - for the entire VisionEval-Dev repo with the VETravelDemandMM package: [Travis-CI Build Status](https://travis-ci.org/cities-lab/VisionEval-Dev)

The previous submission of the package is available at https://github.com/gregorbj/VisionEval/pull/130. The contribution review process for the package is documented there. This resubmission incorporates the feedback from the review process.

### CODE REVIEW

**Comment by DavidOry** [comment]
@dflynn-volpe: the model estimation relies on the `NHTS2009` package. Is this or was this part of VisionEval? I'm only familiar with `VE2001NHTS`.

**Comment by DavidOry** [comment]
@dflynn-volpe: the reliance of the model estimation on non-open data seems problematic and contrary to the spirit of VisionEval (see [here](https://github.com/cities-lab/VETravelDemandMM/blob/7c10bb3e5e9c28ee5ddccdbf0c98da1831a38897/data-raw/LoadDataforModelEst.R#L12). Has this been discussed and resolved previously? What would is a user to do? Is the idea that the models will be distributed as R files but the user cannot recreate or customize the estimation?

**Comment by dflynn-volpe** [comment]
@DavidOry Great point. We discussed this in the initial review ([here](https://github.com/gregorbj/VisionEval/wiki/Meeting-%233-Example-Contribution)), but I can't find in the notes what decision was made about relying on models which are estimated from confidential data like the NHTS 2009. There is this note: 'The group agreed that a subset of the developers (Ben, Brian Gregor, Liming, Tara) should address this question.'

@lmwang9527 you have this package in a public repository: https://github.com/cities-lab/NHTS2009. However, hhctbg.csv is not present, or even described. How can we test the model estimation script?

**Comment by DavidOry** [comment]
While using the confidential data is not ideal because you cannot replicate the estimation work, this doesn't seem to me a reason to not bring the module into the library. The estimation specifications are transparent and having the spatial detail available in the confidential files is probably worth the effort for those interested in using this module. @lmwang9527 has gone out of his way to adhere to the VisionEval's coding procedures and architecture (no small ask). The documentation is excellent and tests are in place. There are some minor things that we'll need to clean up as we bring them into VERSPM, but I think this is as much as we could ask for from a contributor. 

I would ask @lmwang9527 to add a contact or instructions on how to obtain the confidential block group information for the NHTS as well as a data schema for the `hhctbg.csv` file.

**Comment by dflynn-volpe** [comment]
Thank you very much. Yes, please edit the intro vignette to add contact information for NHTS. Also, I think it would be great to document the necessary columns from hhctbg.csv, so the interested user would know what is necessary to recreate a similar file if they have regional travel survey data. You have nice documentation of the output Hh_df file, but can you also add documentation of the input hhctbg.csv?
Such as the columns necessary and data types; i.e., the data scheme Dave referred to. The range of values may also be useful to users, as well.
For example
- HHSTFIPS10, HHCNTYFP10, HHCT10, HHBG10, all factors to concatenate into GEOID10
- HOUSEID, factor, ...
- ... other columns that end up in Hh_df which are from the NHTS 2009 data source.

**Comment by lmwang9527** [comment]
I updated `/data-raw/LoadDataforModelEst.R`, `inst/extdata/sources.md` and `vignettes/review.Rmd` of the `VETravelDemandMM' package with information about the `hhctbg.csv` file and contact information for NHTS. Please let me know if you have any other questions/concerns.

I should point out that I use [`git submodule` functionality](https://github.blog/2016-02-01-working-with-submodules/) to 'point' the `sources/modules/VETravelDemandMM' directory to `https://github.com/cities-lab/VETravelDemandMM`, which I think is a better practice than copying all the files over (and losing all history of the package). Let me know if this is something you'd like to discuss and go over with.

**Comment by dflynn-volpe** [comment]
Thank you again -- yes, I hadn't used `submodule` before, but it is a nice way to keep the package as a separate repository.

**Comment by arashasadabadi** [comment]
@lmwang9527 
I went through the VETravelDeamndMM package and I realize you made it in way that it be the final package of the model thread. But, now I am trying to incorporate VETravelDeamndMM package into visioneval by making a complete model ( like VERSPM). Therefore there are many downstream modules which will use VETravelDeamndMM outputs.  The strategy is bring VETravelDemandMM package alongside other VE packages and call the required modules list from that. Please check the attached file where I explain the issues and changes that we need to implement in order to aggreagete VETravelDemand in a new model and please let me know your feedback

[VERSPM_to_VERSPMMM.docx](https://github.com/VisionEval/VisionEval-Dev/files/2843221/VERSPM_to_VERSPMMM.docx)

**Comment by arashasadabadi** [comment]
@lmwang9527 
As I was testing the model run based on steps I explained in the "VERSPM_to_VERSPMMM.docx" , I faced an error when running "PredictAADVMT" module . After debugging, I realized it is complaining that the "metro" variable is missing. In data specification section "metro" is defined in "Marea" table,   but I checked the datastore and there is not any list called "metro" in "Marea" . Do you know what causes this error?
( The error is : 
all(SegmentCol_vc %in% names(D_df)) is not TRUE )

**Comment by arashasadabadi** [comment]
@lmwang9527

I realized you used "metro" variable to segment households for applying two sets of models to "metro" and "non-metro" residing households. but as I said in last comment, there is not a variable "metro" in datastore to segment households.

I found the similar approach in https://github.com/gregorbj/VisionEval/blob/develop/sources/modules/VEHouseholdTravel/inst/module_docs/CalculateHouseholdDvmt.md

when it applies two "metro" and "non-metro" models. It uses $MSCAT variable from NHTS2001 dataset in estimation process to segment households. However in the main function when it wants to applies the segmented models to data in datastore , it uses Hh_df$LocType which can be "Urban" (=="Metro") or not.

**Comment by arashasadabadi** [comment]
@dflynn-volpe @DavidOry 
I'm still waiting for a response on this. The module cannot be integrated into the existing model unless the issues which I mentioned in previous comments are properly addressed.

**Comment by lmwang9527** [comment]
@arashasadabadi, Marea table needs to have one row for a metro column (with value "metro" or "non-metro") indicating whether the region is a metropolitan or non-metropolitan region for the module to work, as specified in the PredictAADVMTSpecifications. This data specification hasn't been propagated to upstream modules yet, but it needs to be added.  LocationType serves a different purpose than Marea.metro column. 

It'd be better to check in with Brian Gregor to confirm that functions in the VETravelDemandMM are ready to be a drop-in replacement for existing RSPM functions, especially PredictAADVMT, as it predicts Annual Average Daily VMT versus Daily VMT by VEHouseholdVehicles:: CalculateHouseholdDvmt. Brian has some clever post-process to simulate annual average daily VMT from DVMT.

**Comment by arashasadabadi** [comment]
@lmwang9527 
For the first part, yes it needs to be added to the Marea table in one of the beginning modules. The model can't be run now because of this issue so it needs to be fixed for testing the model.
For the second part:
If the purpose here is to integrate VETravelDemandMM into the main framework, we HAVE TO replace VERSPM modules with VETravelDemandMM package modules because they are producing the same metrics.

But, all the questions in "VERSPM_to_VERSPMMM.docx" should be addressed first. The "VMT" and "AAVMT" is one the most important ones.  The replacement of "AssignDrivers" with "PredictDrivers" is also problematic because of different outputs. 

@dflynn-volpe @DavidOry Should I contact Brian?

**Comment by arashasadabadi** [comment]
@dflynn-volpe 

Per discussion in Monday meeting, I tried to test the model without considering the changes for downstream modules( and looking at AADVMT as final product). As mentioned before, the only inconsistency in that case is the "metro" variable. In the current VERSPM setup, the only Marea is "RVMPO" (which clearly is MPO). 
One way to add the "metro" variable is to manually add it to the Marea table somewhere in one of the first modules. If we want the procedure to be automated in model, there should be an input .csv file indicating whether the Mareas are MPO or non-MPO and then they should be assigned to Marea table in datastore in one of the modules ( not sure where is the best place for this to be done). 

Another approach is to take out the metro segmentation in DVMT modelling for now. ( since here we only have one MPO Marea)

Anyways, model can be run and produce AADVMT if metro variable is manually added when running the module .

@lmwang9527

**Comment by jrawbits** [comment]
A series of more recent pull requests have completed the Multi-Modal Module update. See the mm_debug branch.

**Pull request closed without merging**
