### PR TITLE
Patch 12

### PR DESCRIPTION
**Pull request by arashasadabadi**
This pull requests has three components:

1- Adding CalculateSafetyMeasures module to VETravelPerformance package

2- Revisions to VETravelDemandMM package

3- change to visioneval.R in framework to make it consistent with development branch

### CODE REVIEW

**Comment by jrawbits** [comment]
Hi Arash,

I need you to rebase this branch on the 'development' branch of VisionEval-dev.  We still need to reconcile the changes you made to VisionEval.R with those Brian Gregor made separately.

Best,
Jeremy

**Comment by arashasadabadi** [comment]
Hi Jeremy,

Do you still see conflict when merging this?

I can do that but need additional work ( and it may get messy )to get the development and bring all my previous changes to top of that

**Comment by jrawbits** [comment]
Since Brian Gregor made changes to VisionEval.R that embrace the same lines that you changed, we're either going to have to change his code or change your code - and that doesn't necessarily mean "change", but really just reconcile them. I'd suggest finding the corresponding places in his code where you made the changes you needed for the MM Module and just making the changes again in his code.  I'll try to get it to who me the differences and perhaps I can make suggestion s about how to proceed.

**Comment by arashasadabadi** [comment]
@jrawbits I made another pull request to development branch to reconcile the visioneval.R changes. Please use that first. Now visioneval.R is consistent in both of these pull requests.

**Pull request closed without merging**
